### ISSUE TITLE
When I click link from twitter @sailchannels feed I’m getting 404

### ISSUE THREAD

**Issue by markkrueg** [sailingchannels/website#86]
![6D5A02DF-53AD-4E00-9665-15CBEED2D293](https://user-images.githubusercontent.com/12489897/72933192-1e96de00-3d16-11ea-934c-d5b32585c0d5.jpeg)

**Comment by thomasbrueggemann** [comment]
Thanks for reporting, @markkrueg 
I will fix this ASAP!

**Comment by thomasbrueggemann** [comment]
Fixed!
